---
abstract: 'Moose Role for turning ordinary objects into POE sessions'
author:
  - 'Nicholas Perez <nperez@cpan.org>'
generated_by: 'Dist::Zilla version 1.092680'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POEx-Role-SessionInstantiation
requires:
  MooseX::CompileTime::Traits: 0.092801
  MooseX::Declare: 0.31
  POE: 1.269
  POEx::Types: 0.092670
  Test::More: 0.92
resources:
  repository: git://github.com/nperez/psm.git
version: 0.092800
