---
abstract: 'Moose Role for turning ordinary objects into POE sessions'
author:
  - 'Nicholas Perez <nperez@cpan.org>'
generated_by: 'Dist::Zilla::Plugin::MetaYAML version 1.092200'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POEx-Role-SessionInstantiation
requires:
  MooseX::Declare: 0.26
  POE: 1.007
  POEx::Types: 0.091420
  Test::More: 0.92
resources:
  repository: git://github.com/nperez/psm.git
version: 0.092280
