---
abstract: 'A Moose Role for turning objects into POE Sessions'
author:
  - 'Nicholas Perez <nperez@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102340, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POEx-Role-SessionInstantiation
requires:
  MooseX::CompileTime::Traits: 0
  MooseX::Declare: 0
  MooseX::Types: 0
  MooseX::Types::Moose: 0
  POE: 0
  POEx::Types: 0
  aliased: 0
  overload: 0
resources:
  repository: git://github.com/nperez/psm.git
version: 1.102610
